{% set name = "django-taggit" %}
{% set version = "0.22.2" %}
{% set md5 = "9a91a7df4101858654700f7950159d3f" %}
{% set build = 1 %}


package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}

build:
    noarch: python
    number: {{ build }}
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
        - isort
    run:
        - python
        - django >=1.4.5

test:
    imports:
        - taggit
        - taggit.migrations

about:
    home: http://github.com/alex/django-taggit/tree/master
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: django-taggit is a reusable Django application for simple tagging.

extra:
    recipe-maintainers:
        - kwilcox
