{% set name = "django-taggit" %}
{% set version = "0.22.1" %}
{% set md5 = "dd582e2d67c1de20fd2e203584a9ffd4" %}
{% set build = 1 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - django >=1.4.5
        - isort

test:
    imports:
        - taggit
        - taggit.migrations
        - taggit.south_migrations

about:
    home: http://github.com/alex/django-taggit/tree/master
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: django-taggit is a reusable Django application for simple tagging.

extra:
    recipe-maintainers:
        - kwilcox
