{% set version = "6.0.0" %}

package:
  name: django-taggit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-taggit/django_taggit-{{ version }}.tar.gz
  sha256: 723d98bd5c536daa3c0e1bdae0965f7005a9b15269816bb4053fafec4ebad57e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - django >=1.11

test:
  imports:
    - taggit
    - taggit.migrations
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/alex/django-taggit/tree/master
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-taggit is a reusable Django application for simple tagging.

extra:
  recipe-maintainers:
    - kwilcox
    - marcelotrevisani
