{% set version = "1.0.0" %}

package:
  name: django-taggit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-taggit/django-taggit-{{ version }}.tar.gz
  sha256: 01f41e4904f6675e00ddf58a074a7713214f2e2350dab7543c5fee5ef69cc544

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - isort
  run:
    - python
    - django >=1.4.5

test:
  imports:
    - taggit
    - taggit.migrations

about:
  home: http://github.com/alex/django-taggit/tree/master
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-taggit is a reusable Django application for simple tagging.

extra:
  recipe-maintainers:
    - kwilcox
